// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: borobon (https://sketchfab.com/borobon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/7017ab8380264623a3765cfda1e60df8
Title: モップ
*/
'use client'

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { useFrame } from '@react-three/fiber'

export function Moppu(props) {
  const { nodes, materials } = useGLTF('models/scene.gltf')
  const myMesh = useRef()

  // Add directional light for dramatic lighting
  const directionalLight = useRef()
  const ambientLight = useRef()

  useFrame(({ clock }) => {
    const rotationFactor = 0.5
    myMesh.current.rotation.y =
      Math.PI / 1 + Math.tan(clock.getElapsedTime() * rotationFactor)

    // Update directional light position
    directionalLight.current.position.x = Math.sin(clock.getElapsedTime())
    directionalLight.current.position.z = Math.cos(clock.getElapsedTime())
  })
  return (
    <group {...props} dispose={null}>
      {/* Add directional light */}
      <directionalLight
        ref={directionalLight}
        intensity={0.8} // Adjust light intensity
        color="white" // Light color
        position={[0, 20, 0]} // Light position
        castShadow // Enable shadow casting
      />
      {/* Add ambient light */}
      <ambientLight
        ref={ambientLight}
        intensity={0.5} // Adjust ambient light intensity
        color="white" // Light color
      />
      <mesh
        ref={myMesh}
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
        scale={[0.5, 0.5, 0.5]}
        position={(0, 0, 0)} // trying to move model up to top of flex container
      />
    </group>
  )
}

useGLTF.preload('models/scene.gltf')

export default function Model() {
  return (
    <Canvas>
      <Moppu />
    </Canvas>
  )
}
